image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  DB2_HOST: localhost
  DB2_PORT: "50000"
  DB2_USER: db2inst1
  DB2_PASS: mydb2container123
  DB2_DB: testdb
  DB2INST1_PASSWORD: $DB2_PASS
  DBNAME: $DB2_DB

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build

test:
  stage: test

  services:
    - name: itsplus/s2shape-db2-test
      alias: db2

  script:
    - dotnet restore
    - dotnet build
    - dotnet test
