image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  DB2_HOST: db2
  DB2_PORT: "50000"
  DB2_USER: db2inst1
  DB2_PASS: mydb2container123
  DB2_DB: testdb
  DB2INST1_PASSWORD: $DB2_PASS
  DBNAME: $DB2_DB

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test

  services:
    - name: ibmcom/db2
      alias: db2

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/Db2SupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init Db2SupplyCollector server=db2:$DB2_PORT;uid=$DB2_USER;pwd=$DB2_PASS;database=$DB2_DB
    - dotnet SupplyCollectorDataLoader.dll -xunit Db2SupplyCollector server=db2:$DB2_PORT;uid=$DB2_USER;pwd=$DB2_PASS;database=$DB2_DB
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/Db2SupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init Db2SupplyCollector server=db2:$DB2_PORT;uid=$DB2_USER;pwd=$DB2_PASS;database=$DB2_DB
    - dotnet SupplyCollectorDataLoader.dll -xunit Db2SupplyCollector server=db2:$DB2_PORT;uid=$DB2_USER;pwd=$DB2_PASS;database=$DB2_DB
    - dotnet SupplyCollectorDataLoader.dll -samples Db2SupplyCollector server=db2:$DB2_PORT;uid=$DB2_USER;pwd=$DB2_PASS;database=$DB2_DB TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/Db2SupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
